---
title: "Examining the Threat of a 'Twindemic' in New York City"
subtitle: "An Exploratory Analysis of COVID-19 and Influenza vaccination and prevalence patterns in NYC in 2020 and 2021"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

<h5 style="text-align: left;" markdown="1">Group members: Teshawna Badu |  Kiana Chan |  Judy Fordjuoh | Rachelle Juan |  Kelvin Tamakloe </h6>
<br></br>

# Screencast Introduction
<iframe width="560" height="315" src="https://www.youtube.com/embed/gd0XgdkEaVo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


<br>

### Learn about our Project

#### Motivation
As we enter the influenza season this winter while continuing to fight against the COVID-19 pandemic, we have seen a continued urgency from public health and government officials alike, to encourage New Yorkers to get vaccinated for both influenza and COVID-19. This year in particular, experts are concerned that this year's flu season may be even more severe, due to an unusually mild season last year (Spantideas et al, 2021). Now, with the rise of a new COVID variant, city and public health leaders are pushing for mandatory vaccination requirements and continued COVID-19 precautions to prepare for a potential “Twindemic,”; the simultaneous outbreak of influenza and COVID-19. A Twindemic has the potential to crowd emergency rooms, threaten the public health of our communities, and overburden our healthcare system. Therefore, for this project, we seek to conduct an exploratory analysis looking at patterns of COVID-19 and influenza infection rates as well as vaccinations in New York City.  Specifically, we will examine the relationship between COVID-19 and influenza uptake by zip code and sociodemographic factors in New York City through data visualizations and regression analyses. 

<br></br>

#### Related Work
New York City was the epicenter of  COVID-19 during the early stages of the COVID-19 pandemic, with 12,589.2 cases and 404.5 deaths per 100,000 residents recorded in September of 2021 (Moreland et al., 2021). Presently, the emergence of the Omicron variant of the SARS-CoV-2 virus, coinciding with the onset of the winter season means there is the very real threat of a “Twindemic” as has been warned by news outlets and academic sources.  The urgency to encourage vaccination for not only COVID-19, but also influenza, is prevalent now more than ever among city officials and public health professionals in order to curb the spread of two infectious diseases. This is even more important as the COVID-19 pandemic shed light on stark racial/ethnic health disparities related to COVID-19 illness and mortality. Furthermore, vaccine hesitancy has exacerbated these disparities, with more people of color disproportionately affected. We aim for the results of our analyses of the COVID-19 and influenza trends in New York City to inform public health programs and policies to improve vaccination efforts to vulnerable communities.  

<br></br>

### Outline of the Website 
<ul>
<li>[Data Exploration](Data-Exploration.html) : Provides an overview and distribution of the variables in our dataset.<li>
[Data Analysis](Data-Analysis.html) : This provides an analysis of flu and covid clustering.
<li>[Project Report](Project_Report.html) : This is an in-depth write up of our project.

<br></br>

### Connect with Twindemic Team
<ul>
<li>[Teshawna Badu](https://teshawna-lab.github.io/)</li>
<li>[Kiana Chan](https://kianakchanmph.github.io/)</li>
<li>[Judy Fordjuoh](https://jfordjuoh.github.io/)</li>
<li>[Rachelle Juan](https://raj2152.github.io/)</li>
<li>[Kelvin Tamakloe](https://keldel07.github.io/KelDel07i.github.io/index.html)</li>
</ul>