---
title: "Project Report"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

Here we sum everything we did together. 

# Introduction: 
## Motivation
Provide an overview of the project goals and motivation.
As we enter the influenza season this Winter while continuing to fight against the COVID-19 pandemic, we have seen a continued urgency from public health and government officials alike, to encourage New Yorkers to get vaccinated for both influenza and COVID-19. This year in particular, experts are concerned that this year's flu season may be even more severe, due to an unusually mild season last year (Spantideas et al, 2021). Now, with the rise of a new COVID variant, city and public health leaders are pushing for mandatory vaccination requirements and continued COVID-19 precautions to prepare for a potential “Twindemic,” or the simultaneous outbreak of influenza and COVID-19. A Twindemic has the potential to crowd emergency rooms, threaten the public health of our communities, and burden our healthcare system. Therefore, for this project, we seek to conduct an exploratory analysis between COVID-19 and influenza in New York City.  Specifically, we will examine the relationship between COVID-19 and influenza uptake by zip code and sociodemographic factors in New York City through data visualizations and regression analyses. 
 
# Related work: 
Anything that inspired you, such as a paper, a website, or something we discussed in class.
New York City was the epicenter of  COVID-19 during the early stages of the COVID-19 pandemic, with 12,589.2 cases and 404.5 deaths per 100,000 residents recorded in September of 2021 (Moreland et al., 2021). Recently, alongside entering the winter season and the emergence of yet another COVID-19 variant, news outlets and academic sources alike have warned of a threat of a Twindemic. The urgency to get vaccinated for not only COVID-19, but also influenza, is prevalent now more than ever among city officials and public health professionals to curb the spread of two infectious diseases. The COVID-19 pandemic shed light on stark racial/ethnic health disparities related to COVID-19 illness and mortality. Furthermore, vaccine hesitancy has exacerbated these disparities, with more people of color disproportionately affected. We aim for the results of our analyses of the COVID-19 and influenza trends in New York City to inform public health programs and policies to improve vaccination efforts to vulnerable communities. 
 
# Initial questions
A few main questions we had for our exploratory analysis on COVID-19 and influenza in New York City included: 
* What is the relationship between COVID and Flu Vaccination Uptake by Zipcode and Sociodemographic Factors in NYC?
* Option:  What is the difference in COVID and Flu vaccine uptake in NYC, according to  associated sociodemographic factors?
* Option: What are the patterns observed for COVID and Flu vaccine uptake in New York by zip code?
* Option: Difference in COVID and Flu vaccine uptake in NYC and associated sociodemographic factors.
 
 
# Data

### NYC Health COVID-19 
The NYC Department of Health and Mental Hygiene (NYC DOH) classifies the start of the COVID-19 outbreak in NYC by its first lab-confirmed case on February 29, 2020. Cases of COVID-19 included in their datasets are considered “confirmed” cases, or cases with a positive result from a molecular test. NYC DOH data on COVID-19 vaccines come from the Citywide Immunization Registry (CIR), which tracks immunizations for all NYC residents. A person is considered fully vaccinated if they have received both doses of the Moderna or Pfizer vaccine series, or received one dose of the Johnson & Johnson/Janssen vaccine series. There is currently no data on COVID-19 boosters. The NYC DOH COVID-19 data can be found here, and the COVID-19 vaccination data can be found here. 

### New York City Locations Providing Seasonal Flu Vaccine

https://data.cityofnewyork.us/Health/New-York-City-Locations-Providing-Seasonal-Flu-Vac/w9ei-idxz

### Census Data

ZIP Code Data
We also identified a datase that provided the corresponding latitude and longitude for each ZIP code, which we filtered to only include the ZIP codes relevant to our analyses of NYC.

https://gist.github.com/erichurst/7882666

 
Restricting on adults since vaccines weren’t available to children until recently. Therefore, we want to examine the COVID-19 outcomes among adults in this analysis. 
Exploratory analysis: Visualizations, summaries, and exploratory statistical analyses. Justify the steps you took, and show any major changes to your ideas.
 
### Exploratory Analysis 
During our exploratory analysis, we first examined COVID-19 and influenza case and vaccine trends separately to better understand the data we were working with. 
COVID-19 

Add plot image (Weekly Case Rate by Borough)


This plot shows the weekly case rate by NYC borough, beginning the week ending on August 8, 2020. From the plot, we can see that each borough followed a similar trend in cases over time. Cases peaked for all boroughs around January through February of 2021, and then another smaller peak in cases at April 2021. Cases were significantly lower after April 2021, around the time when most NYC adults were eligible to get vaccinated. 

Add plot (Percent adults partially vaccinated by borough)

These plots show the percent of adults partially and fully vaccinated by borough, as of December 2021. The partially vaccinated plot excluded outliers greater than 30% and the fully vaccinated plot excluded outliers greater than 100%, as they were not representative of the dataset and may have been included erroneously. The median full-vaccination rate is greater than 75% for each borough, with Queens, Manhattan, and Staten Island having the highest full-vaccination rates, respectively. Interestingly, while Staten Island has one of the higher vaccination rates, it is consistently the borough with the highest case rate out of all the boroughs. When we examine the partially and fully vaccinated rates cumulatively, each borough is at least 80% vaccinated. 

Add Plot (Distribution of Locations Providing Seasonal Flu Vaccinations)

The above bar graph examines the relationship between locations providing the seasonal flu vaccine and boroughs of NYC. Based on the graph, we can see that Manhattan has by far the largest number of locations providing the flu vaccine, followed by Brooklyn, Queens, the Bronx, and Staten Island, respectively. 

# Additional analysis
If you undertake formal statistical analyses, describe these in detail
 
 Add Graph (NYC COVID Vaccine Locations Clustering Results)
 
# Discussion
What were your findings? Are they what you expect? What insights into the data can you make?


# Limitation
Flu and covid vaccine data did not overlap, explain
